export interface Poem {
  title: string;
  author: string;
  lines: string[];
}

// ai generated
export const FALLBACK_POEMS: Poem[] = [
  {
    title: "I Wandered Lonely as a Cloud",
    author: "William Wordsworth",
    lines: [
      "I wandered lonely as a cloud",
      "That floats on high o'er vales and hills,",
      "When all at once I saw a crowd,",
      "A host, of golden daffodils;",
      "Beside the lake, beneath the trees,",
      "Fluttering and dancing in the breeze.",
      "Continuous as the stars that shine",
      "And twinkle on the milky way,",
      "They stretched in never-ending line",
      "Along the margin of a bay:",
      "Ten thousand saw I at a glance,",
      "Tossing their heads in sprightly dance.",
      "The waves beside them danced; but they",
      "Out-did the sparkling waves in glee:",
      "A poet could not but be gay,",
      "In such a jocund company:",
      "I gazed—and gazed—but little thought",
      "What wealth the show to me had brought:",
      "For oft, when on my couch I lie",
      "In vacant or in pensive mood,",
      "They flash upon that inward eye",
      "Which is the bliss of solitude;",
      "And then my heart with pleasure fills,",
      "And dances with the daffodils.",
    ],
  },
  {
    title: "The Road Not Taken",
    author: "Robert Frost",
    lines: [
      "Two roads diverged in a yellow wood,",
      "And sorry I could not travel both",
      "And be one traveler, long I stood",
      "And looked down one as far as I could",
      "To where it bent in the undergrowth;",
      "Then took the other, as just as fair,",
      "And having perhaps the better claim,",
      "Because it was grassy and wanted wear;",
      "Though as for that the passing there",
      "Had worn them really about the same,",
      "And both that morning equally lay",
      "In leaves no step had trodden black.",
      "Oh, I kept the first for another day!",
      "Yet knowing how way leads on to way,",
      "I doubted if I should ever come back.",
      "I shall be telling this with a sigh",
      "Somewhere ages and ages hence:",
      "Two roads diverged in a wood, and I—",
      "I took the one less traveled by,",
      "And that has made all the difference.",
    ],
  },
  {
    title: "Hope is the thing with feathers",
    author: "Emily Dickinson",
    lines: [
      "Hope is the thing with feathers",
      "That perches in the soul,",
      "And sings the tune without the words,",
      "And never stops at all,",
      "And sweetest in the gale is heard;",
      "And sore must be the storm",
      "That could abash the little bird",
      "Reflecting kept so many warm.",
      "I've heard it in the chillest land,",
      "And on the strangest sea;",
      "Yet, never, in extremity,",
      "It asked a crumb of me.",
    ],
  },
  {
    title: "Sonnet 18: Shall I compare thee to a summer's day?",
    author: "William Shakespeare",
    lines: [
      "Shall I compare thee to a summer's day?",
      "Thou art more lovely and more temperate:",
      "Rough winds do shake the darling buds of May,",
      "And summer's lease hath all too short a date;",
      "Sometime too hot the eye of heaven shines,",
      "And often is his gold complexion dimmed;",
      "And every fair from fair sometime declines,",
      "By chance or nature's changing course untrimmed;",
      "But thy eternal summer shall not fade,",
      "Nor lose possession of that fair thou ow'st;",
      "Nor shall death brag thou wand'rest in his shade,",
      "When in eternal lines to time thou grow'st:",
      "So long as men can breathe or eyes can see,",
      "So long lives this, and this gives life to thee.",
    ],
  },
  {
    title: "Ozymandias",
    author: "Percy Bysshe Shelley",
    lines: [
      "I met a traveller from an antique land,",
      'Who said—"Two vast and trunkless legs of stone',
      "Stand in the desert. . . . Near them, on the sand,",
      "Half sunk a shattered visage lies, whose frown,",
      "And wrinkled lip, and sneer of cold command,",
      "Tell that its sculptor well those passions read",
      "Which yet survive, stamped on these lifeless things,",
      "The hand that mocked them, and the heart that fed;",
      "And on the pedestal, these words appear:",
      "My name is Ozymandias, King of Kings;",
      "Look on my Works, ye Mighty, and despair!",
      "Nothing beside remains. Round the decay",
      "Of that colossal Wreck, boundless and bare",
      "The lone and level sands stretch far away.",
    ],
  },
];